# Generated by Django 5.1.6 on 2025-02-16 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
