# Generated by Django 4.2 on 2025-02-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecategories',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
